cat: scheduler_addr.txt: No such file or directory
Traceback (most recent call last):
  File "/lustre/fswork/projects/rech/jyd/uxd79mv/overload_test/adaptative/src/analytics.py", line 20, in <module>
    scheduler_addr= str(sys.argv[1])
                        ~~~~~~~~^^^
IndexError: list index out of range
srun: error: r1i0n21: task 0: Exited with exit code 1
srun: Terminating StepId=556841.1
srun: Job step aborted: Waiting up to 62 seconds for job step to finish.
slurmstepd: error: *** STEP 556841.0 ON r1i0n21 CANCELLED AT 2025-06-25T13:34:43 ***
slurmstepd: error: *** JOB 556841 ON r1i0n21 CANCELLED AT 2025-06-25T13:34:43 ***
